version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-net

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
